networks:
    development:
        gas_limit: max
        gas_buffer: 1
        gas_price: 0
        max_fee: null
        priority_fee: null
        reverting_tx_gas_limit: max
        default_contract_owner: true
        cmd_settings:
            port: 8545
            gas_limit: 88888888888
            accounts: 10
            chain_id: 1
            network_id: 1588949648
            evm_version: istanbul
            fork: https://rpc.ankr.com/eth@15259100
            mnemonic: brownie
            default_balance: 10000000000000
            unlock: null
compiler:
    evm_version: null
    solc:
        version: null
        optimizer:
            enabled: true
            runs: 200
    vyper:
        version: 0.3.3
